# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the relevant issue template!
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines [here](https://github.com/farhan7reza7/diff-ymd-package/blob/main/CONTRIBUTING.md).

# Comment to be posted to on Pr's merged by a first time user
firstPRMergeComment: >

blank_issues_enabled: false
contact_links:
  - name: ğŸ—£ Ask a Question, Discuss
    url: https://github.com/eslint/eslint/discussions
    about: Get help using ESLint
  - name: ğŸ“ Help with VS Code ESLint
    url: https://github.com/microsoft/vscode-eslint/issues/
    about: Bugs and feature requests for the VS Code ESLint plugin
  - name: Discord Server
    url: https://eslint.org/chat
    about: Talk with the team
